-- AutomaticTools platform - PostgreSQL initial schema
-- Monetary amounts are stored in cents. Time fields are Unix timestamps in seconds.

BEGIN;

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(32) NOT NULL UNIQUE,
    email VARCHAR(254) CHECK (email IS NULL OR BTRIM(email) <> ''),
    phone VARCHAR(32) CHECK (phone IS NULL OR BTRIM(phone) <> ''),
    password_hash TEXT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'disabled')),
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    last_login_at BIGINT
);

-- Existing databases may already have users without contact columns.
ALTER TABLE users
    ADD COLUMN IF NOT EXISTS email VARCHAR(254)
        CHECK (email IS NULL OR BTRIM(email) <> '');

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS phone VARCHAR(32)
        CHECK (phone IS NULL OR BTRIM(phone) <> '');

COMMENT ON TABLE users IS '平台用户账号';
COMMENT ON COLUMN users.id IS '用户主键ID';
COMMENT ON COLUMN users.username IS '登录用户名，全局唯一';
COMMENT ON COLUMN users.email IS '用户邮箱，可为空，填写后忽略大小写全局唯一';
COMMENT ON COLUMN users.phone IS '用户手机号，可为空，填写后全局唯一';
COMMENT ON COLUMN users.password_hash IS '经bcrypt加密后的密码哈希';
COMMENT ON COLUMN users.status IS '账号状态：active正常，disabled停用';
COMMENT ON COLUMN users.created_at IS '创建时间，Unix秒级时间戳';
COMMENT ON COLUMN users.updated_at IS '最后更新时间，Unix秒级时间戳';
COMMENT ON COLUMN users.last_login_at IS '最后登录时间，Unix秒级时间戳';

CREATE UNIQUE INDEX IF NOT EXISTS uq_users_email
    ON users(LOWER(email)) WHERE email IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_users_phone
    ON users(phone) WHERE phone IS NOT NULL;

CREATE TABLE IF NOT EXISTS tools (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(64) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    price_cents BIGINT NOT NULL CHECK (price_cents >= 0),
    currency CHAR(3) NOT NULL DEFAULT 'CNY',
    lifetime BOOLEAN NOT NULL DEFAULT TRUE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at BIGINT NOT NULL
);

COMMENT ON TABLE tools IS '平台可购买的工具商品';
COMMENT ON COLUMN tools.id IS '工具主键ID';
COMMENT ON COLUMN tools.code IS '工具唯一编码，客户端与后端共同使用';
COMMENT ON COLUMN tools.name IS '工具展示名称';
COMMENT ON COLUMN tools.description IS '工具功能说明';
COMMENT ON COLUMN tools.price_cents IS '销售价格，单位为分';
COMMENT ON COLUMN tools.currency IS '三位货币代码，默认CNY';
COMMENT ON COLUMN tools.lifetime IS '是否为买断后永久使用';
COMMENT ON COLUMN tools.active IS '是否上架可购买';
COMMENT ON COLUMN tools.created_at IS '创建时间，Unix秒级时间戳';

CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no VARCHAR(64) NOT NULL UNIQUE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    tool_code VARCHAR(64) NOT NULL REFERENCES tools(code),
    amount_cents BIGINT NOT NULL CHECK (amount_cents >= 0),
    currency CHAR(3) NOT NULL DEFAULT 'CNY',
    status VARCHAR(20) NOT NULL
        CHECK (status IN ('pending', 'paid', 'cancelled', 'failed', 'refunded')),
    pay_channel VARCHAR(32) NOT NULL DEFAULT '',
    provider_trade_no VARCHAR(64) NOT NULL DEFAULT '',
    payment_qr_code TEXT NOT NULL DEFAULT '',
    payment_expires_at BIGINT,
    paid_at BIGINT,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
);

-- Keep the canonical schema safe for databases created by older releases.
-- These columns are repeated in migration 005 so either startup path remains
-- idempotent.
ALTER TABLE orders
    ADD COLUMN IF NOT EXISTS provider_trade_no VARCHAR(64) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS payment_qr_code TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS payment_expires_at BIGINT;

COMMENT ON TABLE orders IS '用户购买工具的支付订单';
COMMENT ON COLUMN orders.id IS '订单主键ID';
COMMENT ON COLUMN orders.order_no IS '平台订单号，全局唯一';
COMMENT ON COLUMN orders.user_id IS '下单用户ID';
COMMENT ON COLUMN orders.tool_code IS '购买的工具编码';
COMMENT ON COLUMN orders.amount_cents IS '订单实际金额，单位为分';
COMMENT ON COLUMN orders.currency IS '三位货币代码';
COMMENT ON COLUMN orders.status IS '订单状态：pending待支付，paid已支付，cancelled已取消，failed失败，refunded已退款';
COMMENT ON COLUMN orders.pay_channel IS '支付渠道编码';
COMMENT ON COLUMN orders.provider_trade_no IS '支付渠道交易号，例如支付宝交易号';
COMMENT ON COLUMN orders.payment_qr_code IS '支付渠道返回的二维码内容，仅待支付阶段使用';
COMMENT ON COLUMN orders.payment_expires_at IS '支付二维码失效时间，Unix秒级时间戳';
COMMENT ON COLUMN orders.paid_at IS '支付成功时间，Unix秒级时间戳';
COMMENT ON COLUMN orders.created_at IS '创建时间，Unix秒级时间戳';
COMMENT ON COLUMN orders.updated_at IS '最后更新时间，Unix秒级时间戳';

CREATE INDEX IF NOT EXISTS idx_orders_user_id_created_at
    ON orders(user_id, created_at DESC);

CREATE UNIQUE INDEX IF NOT EXISTS uk_orders_provider_trade_no
    ON orders(provider_trade_no)
    WHERE provider_trade_no <> '';

CREATE TABLE IF NOT EXISTS entitlements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    tool_code VARCHAR(64) NOT NULL REFERENCES tools(code),
    source VARCHAR(32) NOT NULL,
    order_no VARCHAR(64),
    expires_at BIGINT,
    created_at BIGINT NOT NULL,
    UNIQUE (user_id, tool_code)
);

COMMENT ON TABLE entitlements IS '用户已获得的工具使用权限';
COMMENT ON COLUMN entitlements.id IS '权限主键ID';
COMMENT ON COLUMN entitlements.user_id IS '权限所属用户ID';
COMMENT ON COLUMN entitlements.tool_code IS '已授权的工具编码';
COMMENT ON COLUMN entitlements.source IS '权限来源，例如order、admin';
COMMENT ON COLUMN entitlements.order_no IS '关联订单号，手工授权时可为空';
COMMENT ON COLUMN entitlements.expires_at IS '权限到期时间，为空表示永久，Unix秒级时间戳';
COMMENT ON COLUMN entitlements.created_at IS '创建时间，Unix秒级时间戳';

CREATE INDEX IF NOT EXISTS idx_entitlements_user_id
    ON entitlements(user_id);

CREATE TABLE IF NOT EXISTS devices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    device_id VARCHAR(255) NOT NULL,
    device_name VARCHAR(255) NOT NULL DEFAULT '',
    platform VARCHAR(32) NOT NULL,
    last_seen_at BIGINT NOT NULL,
    created_at BIGINT NOT NULL,
    UNIQUE (user_id, device_id)
);

COMMENT ON TABLE devices IS '用户绑定的客户端设备';
COMMENT ON COLUMN devices.id IS '设备绑定主键ID';
COMMENT ON COLUMN devices.user_id IS '设备所属用户ID';
COMMENT ON COLUMN devices.device_id IS '客户端生成的设备唯一标识';
COMMENT ON COLUMN devices.device_name IS '设备展示名称';
COMMENT ON COLUMN devices.platform IS '客户端平台，例如android、windows';
COMMENT ON COLUMN devices.last_seen_at IS '设备最后访问时间，Unix秒级时间戳';
COMMENT ON COLUMN devices.created_at IS '首次绑定时间，Unix秒级时间戳';

CREATE INDEX IF NOT EXISTS idx_devices_user_id_last_seen_at
    ON devices(user_id, last_seen_at DESC);

CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    action VARCHAR(100) NOT NULL,
    ip VARCHAR(64) NOT NULL DEFAULT '',
    user_agent TEXT NOT NULL DEFAULT '',
    detail TEXT NOT NULL DEFAULT '',
    created_at BIGINT NOT NULL
);

COMMENT ON TABLE audit_logs IS '关键业务操作审计日志';
COMMENT ON COLUMN audit_logs.id IS '审计日志主键ID';
COMMENT ON COLUMN audit_logs.user_id IS '关联用户ID，用户删除后保留日志并置空';
COMMENT ON COLUMN audit_logs.action IS '操作类型编码';
COMMENT ON COLUMN audit_logs.ip IS '请求来源IP地址';
COMMENT ON COLUMN audit_logs.user_agent IS '请求User-Agent';
COMMENT ON COLUMN audit_logs.detail IS '操作详细信息';
COMMENT ON COLUMN audit_logs.created_at IS '创建时间，Unix秒级时间戳';

CREATE INDEX IF NOT EXISTS idx_audit_logs_user_id_created_at
    ON audit_logs(user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_audit_logs_action_created_at
    ON audit_logs(action, created_at DESC);

INSERT INTO tools (
    code,
    name,
    description,
    price_cents,
    currency,
    lifetime,
    active,
    created_at
) VALUES (
    'auto_click',
    '自动点击',
    '基础自动点击工具，购买后永久使用。',
    1000,
    'CNY',
    TRUE,
    TRUE,
    EXTRACT(EPOCH FROM CURRENT_TIMESTAMP)::BIGINT
)
ON CONFLICT (code) DO NOTHING;

COMMIT;
