-- Add administrator accounts for management APIs.

BEGIN;

CREATE TABLE IF NOT EXISTS admins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(32) NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'disabled')),
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    last_login_at BIGINT
);

COMMENT ON TABLE admins IS '管理端管理员账号';
COMMENT ON COLUMN admins.id IS '管理员主键ID';
COMMENT ON COLUMN admins.username IS '管理员登录用户名，全局唯一';
COMMENT ON COLUMN admins.password_hash IS '经bcrypt加密后的密码哈希';
COMMENT ON COLUMN admins.status IS '账号状态：active正常，disabled停用';
COMMENT ON COLUMN admins.created_at IS '创建时间，Unix秒级时间戳';
COMMENT ON COLUMN admins.updated_at IS '最后更新时间，Unix秒级时间戳';
COMMENT ON COLUMN admins.last_login_at IS '最后登录时间，Unix秒级时间戳';

COMMIT;
