-- Add one-time email verification codes used during user registration.

BEGIN;

CREATE TABLE IF NOT EXISTS email_verification_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(254) NOT NULL,
    purpose VARCHAR(32) NOT NULL
        CHECK (purpose IN ('register')),
    code_hash CHAR(64) NOT NULL,
    expires_at BIGINT NOT NULL,
    consumed_at BIGINT,
    attempt_count INTEGER NOT NULL DEFAULT 0
        CHECK (attempt_count >= 0),
    created_at BIGINT NOT NULL
);

COMMENT ON TABLE email_verification_codes IS '邮箱一次性验证码记录';
COMMENT ON COLUMN email_verification_codes.id IS '验证码记录主键ID';
COMMENT ON COLUMN email_verification_codes.email IS '规范化后的小写邮箱地址';
COMMENT ON COLUMN email_verification_codes.purpose IS '验证码用途，目前为register注册';
COMMENT ON COLUMN email_verification_codes.code_hash IS '使用服务端密钥计算的验证码HMAC-SHA256哈希';
COMMENT ON COLUMN email_verification_codes.expires_at IS '验证码过期时间，Unix秒级时间戳';
COMMENT ON COLUMN email_verification_codes.consumed_at IS '验证码使用或失效时间，Unix秒级时间戳';
COMMENT ON COLUMN email_verification_codes.attempt_count IS '验证码错误尝试次数';
COMMENT ON COLUMN email_verification_codes.created_at IS '验证码发送时间，Unix秒级时间戳';

CREATE INDEX IF NOT EXISTS idx_email_verification_codes_lookup
    ON email_verification_codes(email, purpose, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_email_verification_codes_cleanup
    ON email_verification_codes(expires_at);

COMMIT;
