BEGIN;

CREATE TABLE IF NOT EXISTS license_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_hash CHAR(64) NOT NULL UNIQUE,
    code_hint VARCHAR(24) NOT NULL,
    tool_code VARCHAR(64) NOT NULL REFERENCES tools(code),
    batch_no VARCHAR(64) NOT NULL,
    note VARCHAR(200) NOT NULL DEFAULT '',
    status VARCHAR(20) NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'redeemed', 'revoked')),
    created_by_admin_id BIGINT REFERENCES admins(id) ON DELETE SET NULL,
    redeemed_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    redeemed_at BIGINT,
    revoked_at BIGINT,
    created_at BIGINT NOT NULL,
    CHECK (
        (status = 'active' AND redeemed_by_user_id IS NULL AND redeemed_at IS NULL AND revoked_at IS NULL)
        OR (status = 'redeemed' AND redeemed_by_user_id IS NOT NULL AND redeemed_at IS NOT NULL AND revoked_at IS NULL)
        OR (status = 'revoked' AND redeemed_by_user_id IS NULL AND redeemed_at IS NULL AND revoked_at IS NOT NULL)
    )
);

COMMENT ON TABLE license_codes IS '工具一次性授权码库存';
COMMENT ON COLUMN license_codes.id IS '授权码记录ID';
COMMENT ON COLUMN license_codes.code_hash IS '规范化授权码的SHA-256摘要，不保存可兑换明文';
COMMENT ON COLUMN license_codes.code_hint IS '用于后台识别的授权码尾号提示';
COMMENT ON COLUMN license_codes.tool_code IS '兑换后获得的工具编码';
COMMENT ON COLUMN license_codes.batch_no IS '批量生成时的批次号';
COMMENT ON COLUMN license_codes.note IS '批次备注或销售渠道说明';
COMMENT ON COLUMN license_codes.status IS '状态：active未使用，redeemed已兑换，revoked已作废';
COMMENT ON COLUMN license_codes.created_by_admin_id IS '生成授权码的管理员ID';
COMMENT ON COLUMN license_codes.redeemed_by_user_id IS '成功兑换的用户ID';
COMMENT ON COLUMN license_codes.redeemed_at IS '兑换时间，Unix秒级时间戳';
COMMENT ON COLUMN license_codes.revoked_at IS '作废时间，Unix秒级时间戳';
COMMENT ON COLUMN license_codes.created_at IS '生成时间，Unix秒级时间戳';

CREATE INDEX IF NOT EXISTS idx_license_codes_status_created_at
    ON license_codes(status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_license_codes_tool_code_created_at
    ON license_codes(tool_code, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_license_codes_batch_no
    ON license_codes(batch_no);

CREATE INDEX IF NOT EXISTS idx_license_codes_redeemed_user
    ON license_codes(redeemed_by_user_id)
    WHERE redeemed_by_user_id IS NOT NULL;

COMMIT;
