BEGIN;

-- 玩家游戏数据
CREATE TABLE IF NOT EXISTS game_players (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
    nickname VARCHAR(32) NOT NULL DEFAULT '',
    level INT NOT NULL DEFAULT 1,
    exp BIGINT NOT NULL DEFAULT 0,
    gold BIGINT NOT NULL DEFAULT 0,
    combat_power BIGINT NOT NULL DEFAULT 0,
    wins INT NOT NULL DEFAULT 0,
    losses INT NOT NULL DEFAULT 0,
    box_pity_counter INT NOT NULL DEFAULT 0,
    daily_challenge_count INT NOT NULL DEFAULT 0,
    daily_challenge_date DATE NOT NULL DEFAULT CURRENT_DATE,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
);

COMMENT ON TABLE game_players IS '玩家游戏核心数据';
COMMENT ON COLUMN game_players.user_id IS '关联用户系统ID';
COMMENT ON COLUMN game_players.level IS '角色等级';
COMMENT ON COLUMN game_players.exp IS '当前经验值';
COMMENT ON COLUMN game_players.gold IS '金币数量';
COMMENT ON COLUMN game_players.combat_power IS '总战力';
COMMENT ON COLUMN game_players.wins IS '累计胜场';
COMMENT ON COLUMN game_players.losses IS '累计败场';
COMMENT ON COLUMN game_players.box_pity_counter IS '开箱保底计数器';
COMMENT ON COLUMN game_players.daily_challenge_count IS '今日已挑战次数';
COMMENT ON COLUMN game_players.daily_challenge_date IS '挑战次数对应的日期';

-- 装备模板定义
CREATE TABLE IF NOT EXISTS game_equipment_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
    slot VARCHAR(20) NOT NULL CHECK (slot IN ('weapon', 'helmet', 'armor', 'shield', 'accessory')),
    rarity INT NOT NULL CHECK (rarity BETWEEN 1 AND 5),
    base_atk INT NOT NULL DEFAULT 0,
    base_def INT NOT NULL DEFAULT 0,
    base_hp INT NOT NULL DEFAULT 0,
    base_spd INT NOT NULL DEFAULT 0,
    icon_path VARCHAR(200) NOT NULL DEFAULT '',
    description VARCHAR(200) NOT NULL DEFAULT '',
    created_at BIGINT NOT NULL
);

COMMENT ON TABLE game_equipment_templates IS '装备模板定义表';
COMMENT ON COLUMN game_equipment_templates.slot IS '装备槽位: weapon/helmet/armor/shield/accessory';
COMMENT ON COLUMN game_equipment_templates.rarity IS '稀有度: 1白 2绿 3蓝 4紫 5橙';
COMMENT ON COLUMN game_equipment_templates.base_atk IS '基础攻击力';
COMMENT ON COLUMN game_equipment_templates.base_def IS '基础防御力';
COMMENT ON COLUMN game_equipment_templates.base_hp IS '基础生命值';
COMMENT ON COLUMN game_equipment_templates.base_spd IS '基础速度';

-- 玩家装备背包
CREATE TABLE IF NOT EXISTS game_player_equipments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id BIGINT NOT NULL REFERENCES game_players(id) ON DELETE CASCADE,
    template_id BIGINT NOT NULL REFERENCES game_equipment_templates(id),
    rarity INT NOT NULL CHECK (rarity BETWEEN 1 AND 5),
    atk INT NOT NULL DEFAULT 0,
    def INT NOT NULL DEFAULT 0,
    hp INT NOT NULL DEFAULT 0,
    spd INT NOT NULL DEFAULT 0,
    bonus_attrs JSONB NOT NULL DEFAULT '[]',
    equipped BOOLEAN NOT NULL DEFAULT FALSE,
    obtained_at BIGINT NOT NULL
);

COMMENT ON TABLE game_player_equipments IS '玩家拥有的装备实例';
COMMENT ON COLUMN game_player_equipments.bonus_attrs IS '随机附加词条JSON数组';
COMMENT ON COLUMN game_player_equipments.equipped IS '是否已装备';

CREATE INDEX IF NOT EXISTS idx_player_equipments_player_id
    ON game_player_equipments(player_id);
CREATE INDEX IF NOT EXISTS idx_player_equipments_player_slot
    ON game_player_equipments(player_id, equipped);

-- 战斗记录
CREATE TABLE IF NOT EXISTS game_battles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attacker_id BIGINT NOT NULL REFERENCES game_players(id),
    defender_id BIGINT NOT NULL REFERENCES game_players(id),
    winner_id BIGINT NOT NULL REFERENCES game_players(id),
    battle_log JSONB NOT NULL DEFAULT '[]',
    reward_gold BIGINT NOT NULL DEFAULT 0,
    reward_exp BIGINT NOT NULL DEFAULT 0,
    created_at BIGINT NOT NULL
);

COMMENT ON TABLE game_battles IS '异步PK战斗记录';
COMMENT ON COLUMN game_battles.battle_log IS '战斗过程日志，用于客户端回放';

CREATE INDEX IF NOT EXISTS idx_battles_attacker
    ON game_battles(attacker_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_battles_defender
    ON game_battles(defender_id, created_at DESC);

-- 排行榜
CREATE TABLE IF NOT EXISTS game_leaderboard (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id BIGINT NOT NULL REFERENCES game_players(id) ON DELETE CASCADE,
    rank_type VARCHAR(20) NOT NULL CHECK (rank_type IN ('power', 'wins')),
    score BIGINT NOT NULL DEFAULT 0,
    rank INT NOT NULL DEFAULT 0,
    updated_at BIGINT NOT NULL,
    UNIQUE(player_id, rank_type)
);

COMMENT ON TABLE game_leaderboard IS '排行榜缓存表';

CREATE INDEX IF NOT EXISTS idx_leaderboard_type_score
    ON game_leaderboard(rank_type, score DESC);

-- 开箱记录
CREATE TABLE IF NOT EXISTS game_box_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id BIGINT NOT NULL REFERENCES game_players(id) ON DELETE CASCADE,
    box_type VARCHAR(20) NOT NULL DEFAULT 'normal',
    result_equipment_id BIGINT REFERENCES game_player_equipments(id),
    is_pity BOOLEAN NOT NULL DEFAULT FALSE,
    created_at BIGINT NOT NULL
);

COMMENT ON TABLE game_box_records IS '开箱历史记录';

CREATE INDEX IF NOT EXISTS idx_box_records_player
    ON game_box_records(player_id, created_at DESC);

COMMIT;
